services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: nitesh1508/docker-fullstack-backend:v1
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo_data:
